### ISSUE TITLE
Ores set to generate in wood planks.

### ISSUE THREAD

**Issue by Kiroto** [arthurbambou/Randomly-Adding-Anything#10]
I found that an ore can generate in wooden planks, and the way to mine it isn't by using an axe, but a shovel instead.

I believe this should be removed, but only partially.

Stone is stone and the ores are valuable, right?
How about wood is wood, and special wood is valuable? I'm talking about randomized special hardwood that also requires axe progression.

This would be a nice way to implement new trees into the mix. These trees's sapling yield and tool durability should tend to be low (so they depend on farming), however their speed, power and damage could be as randomized as other randomly generated stuffs.
For balancing, some trees could yield only 3 planks per log, and others 5. Yielding more or less planks could counter-balance tool efficiency.

If the player doesn't want to use that wood for tools because it looks beautiful, it should also have it's full furniture set.
_I already have some of the sprites grayscaled and masked (two colors in the same picture) if needed._

**Comment by oliviathevampire** [comment]
The ores with planks is temporary to show the ores that dosen''t generatte in the world

**Comment by oliviathevampire** [comment]
will be fixed in a future update
