### ISSUE TITLE
I can't figure out how to download/install I have twitch but its not working

### ISSUE THREAD

**Issue by theseabasher** [arthurbambou/Randomly-Adding-Anything#100]
Twitch doesn't show it when I go to install a mod and it doesn't work when I add it to my mods list and go on forge

**Comment by oliviathevampire** [comment]
Solution: Not use twitch


But seriously, if you realllllly wanna use Twitch use a mod called Jumploader. But I really don’t reccomend Twitch for fabric modpacks.

**Comment by theseabasher** [comment]
Then how would I install it? because Im very new to mc mods but when I put it into my mods folder it doesn't work with forge and I have fabric and api

**Comment by theseabasher** [comment]
Nevermind! Got it to work thank you for helping anyway
