### ISSUE TITLE
Game crashed when placing block

### ISSUE THREAD

**Issue by Graph06** [arthurbambou/Randomly-Adding-Anything#101]
Tried placing a block generated by the mod and it crashed. I have attached the crash report here:
[crash-2020-06-05_14.27.34-client.txt](https://github.com/vampire-studios/Randomly-Adding-Anything/files/4737846/crash-2020-06-05_14.27.34-client.txt)

**Comment by oliviathevampire** [comment]
Should be fixed in this version https://www.curseforge.com/minecraft/mc-mods/randomly-adding-anything/files/2976313
