### ISSUE TITLE
Ores don't render with OptiFine installed

### ISSUE THREAD

**Issue by cs127** [arthurbambou/Randomly-Adding-Anything#102]
When OptiFine is installed, the ores are invisible in the inventory, and in the world, not only they are invisible, but the blocks behind them are also not rendered.

Minecraft version: 1.15.2
Fabric loader version: 0.8.7 build 201
Fabric API version: 0.11.1 build 312
OptiFine version: G1 pre23
OptiFabric version: 1.0.0 beta 8

**Comment by oliviathevampire** [comment]
This is intentional game design for us, it fixes that the game would otherwise crash.

**Comment by cs127** [comment]
wait so I shouldn't use optifine?

**Comment by oliviathevampire** [comment]
not really, cause it changes how a lot of rendering is done, you should instead try fabric mods like Sodium and Phosphor, they improve performance a lot.
