### ISSUE TITLE
Invisible Ores with Sodium (Please make compatible)

### ISSUE THREAD

**Issue by mattstat716** [arthurbambou/Randomly-Adding-Anything#104]
Please, make this compatible with Sodium. Sodium is simply too good for me to give up - it boosts FPS to incredible amounts.

**Comment by Moctor42** [comment]
I'm having the same issue, would be nice to have them compatible seeing as it's a pretty essential mod

**Comment by oliviathevampire** [comment]
This has the same problem as we have with Optifine, their changing how rendering works so it fucks up every mod that depends on for example Fabric API renderer

**Comment by thecatcore** [comment]
Sodium is not compatible with the Fabric Rendering API yet, Sodium’s dev are working on it.
