### ISSUE TITLE
My game would not start while trying to play with the mod installed

### ISSUE THREAD

**Issue by Dumpsterhead** [arthurbambou/Randomly-Adding-Anything#15]
Is there a fix to this, or you guys already working on it?

**Comment by thecatcore** [comment]
Do you have Fabric API installed?

**Comment by thecatcore** [comment]
Fixed by [c29ac86](https://github.com/vampire-studios/Randomly-Adding-Anything/commit/c29ac8620986d1ad404f405ed934647e1ae5232d) and released on curseforge.
