### ISSUE TITLE
Optifabric/Optifine can't load specific ore

### ISSUE THREAD

**Issue by Twistkit** [arthurbambou/Randomly-Adding-Anything#22]
When I go into the menu with this specific ore, it saves the world and promptly crashes. What do I do?

**Comment by RViper80** [comment]
Yep, something with the way Optifabric/fine modifies the renderer crashes the game upon scrolling to your ore blocks in REI.

REI Crash Log: https://pastebin.com/nSxRnMJT

Edit:  Noticed that the ores are fine in the world, but if I try to look at them (using The One Probe) then it crashes the game as well.

The One Probe Crash Log: https://pastebin.com/e5zj4M1K

**Comment by Twistkit** [comment]
Is there a way to fix it?
