### ISSUE TITLE
Crashing when Retrieving Items

### ISSUE THREAD

**Issue by YummyYoda** [arthurbambou/Randomly-Adding-Anything#27]
when mining certain ores, the game crashes and gives me this message in the launcher:
<img width="355" alt="Screenshot (16)" src="https://user-images.githubusercontent.com/56615563/66880147-60292780-ef76-11e9-8c6b-4eced28724a2.png">

**Comment by thecatcore** [comment]
Have you installed Optifine?

**Comment by YummyYoda** [comment]
yep. and, of course, optifabric as well

**Comment by YummyYoda** [comment]
here's a crash report if you need to see it
[crash_report_infinite_minecraft.txt](https://github.com/vampire-studios/Randomly-Adding-Anything/files/3736750/crash_report_infinite_minecraft.txt)

**Comment by thecatcore** [comment]
RAA is incompatible with Optifine/Optifabric.

**Comment by thecatcore** [comment]
Fixed
