### ISSUE TITLE
Project ReadMe

### ISSUE THREAD

**Issue by Kiroto** [arthurbambou/Randomly-Adding-Anything#4]
Right now the `README.md` is empty, and I feel kind of lost when looking at the project (Specially because I haven't programmed in java -- I can understand some of it).

I believe it'd be good to have current mod features and information on the readme, and perhaps a roadmap regarding planned features and whatnot. Perhaps also how to help.
_I'll try and help this project whenever I feel inspired~_

**Comment by thecatcore** [comment]
[de43116bf](https://github.com/vampire-studios/Randomly-Adding-Anything/commit/de43116bfceb09961a9adf2911ecfcaca1c66c33) add more info to ReadMe

**Comment by thecatcore** [comment]
Fixed by #9
