### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Preston9999** [arthurbambou/Randomly-Adding-Anything#46]
I am new to fabric and mods in general but when ever I try to play I get the message saying it can not be loaded and that the Fabric mod can not be loaded, I have Fabric API downloaded and I am trying to do this on minecraft 1.14.4, I do not have any other mods downloaded  just this one, what is wrong?
![Capture](https://user-images.githubusercontent.com/42789185/71324188-d6cc2f00-24a9-11ea-8213-cdb8d425f88a.PNG)

**Comment by oliviathevampire** [comment]
your running it using forge, that's not possible
