### ISSUE TITLE
Every time I leave a world, I can't get back in without crashing the game. Problem started in 1.15.1 version with dimention update

### ISSUE THREAD

**Issue by StriletsGlib** [arthurbambou/Randomly-Adding-Anything#49]
If you set dimentions to 0, there are instant crash problem vanishes. If I understand anything, " " is not liked by Minecraft and crashes game as a revenge.

[crash-2019-12-27_18.24.39-server.txt](https://github.com/vampire-studios/Randomly-Adding-Anything/files/4005768/crash-2019-12-27_18.24.39-server.txt)

Dimention Materials are bugged out in recepies (which sometimes leads you to craft armor pieces out of nothing), but devs already know that.

**Comment by StriletsGlib** [comment]
P S also some dimention cause insta crush.

**Comment by Twistkit** [comment]
Having these exact same problems. Going to leave crash reports in this comment.
Tring to enter the world:

[Minecraft Crash Report.txt](https://github.com/vampire-studios/Randomly-Adding-Anything/files/4006170/Minecraft.Crash.Report.txt)

Entering a portal just crashes the game with no crash report.

**Comment by StriletsGlib** [comment]
This build fixed that. Thank's Olivia!
https://github.com/vampire-studios/Randomly-Adding-Anything/releases/tag/2.0.1%2Bbuild.435-1.15.1
P. S. download raa-2.0.1+build.435.jar file and replace your old mod file with this one.
