### ISSUE TITLE
Missing Textures for some Ores

### ISSUE THREAD

**Issue by Twistkit** [arthurbambou/Randomly-Adding-Anything#50]
Some Ores have missing textures. I have left an example below.

![image](https://user-images.githubusercontent.com/54967356/71531230-b93d0200-28bb-11ea-996a-a11bfa576977.png)

This ore in general makes a grass sound when you break it, yet there are still grass ores with textures in the menu.

Also for some reason, no ores are generating??? Might just be a one-off chance though.

**Comment by StriletsGlib** [comment]
I think your ores might be in other dimentions

**Comment by GyroFox** [comment]
I can also find untextured ores in my creative inventory, however when i try to place it, the game crashes.

**Comment by Twistkit** [comment]
Happens to me too now in build 436. 
Here is the [crash report](https://github.com/vampire-studios/Randomly-Adding-Anything/files/4006523/crash-2019-12-27_19.38.01-client.txt)

**Comment by thecatcore** [comment]
Fixed by 1e4ff2a35ed282e112779d5960d940637602a8eb and 365ec30eef181e1340342b1fde7d122a89fd8f27
