### ISSUE TITLE
Helmet crafting recipe

### ISSUE THREAD

**Issue by GyroFox** [arthurbambou/Randomly-Adding-Anything#51]
When using a crafting table, after putting anything in and then taking it back out, i am able to craft a helmet from nothing.
![huh](https://user-images.githubusercontent.com/59297236/71535829-07282900-2901-11ea-83c0-4109af2dce18.png)

**Comment by GyroFox** [comment]
I'm also able to craft a sword with a single stick.
![huh](https://user-images.githubusercontent.com/59297236/71535903-ced51a80-2901-11ea-84b7-9593cd335514.png)

**Comment by StriletsGlib** [comment]
Try crafting tools with pair of sticks...
Devs know that this is happening. Something with crafting recepies not registering ores from RA dimentions. (resources have two words in them...)

**Comment by GyroFox** [comment]
If by pair of sticks you mean like the shovel recipe, then it works for that too.
![huh](https://user-images.githubusercontent.com/59297236/71536379-6c324d80-2906-11ea-94a6-04593459006a.png)

**Comment by thecatcore** [comment]
natanfudge/artifice#1
