### ISSUE TITLE
Placing certain blocks crashes the game.

### ISSUE THREAD

**Issue by Braxiations** [arthurbambou/Randomly-Adding-Anything#60]
Crash message:

The game crashed whilst tesselating block in world - indigo renderer
Error: java.lang.NullPointerException: Tesselating block in world - Indigo Renderer

**Comment by thecatcore** [comment]
can you send the crashlog? What was the block you tryed to place? What was the version of the mod you were using?

**Comment by Braxiations** [comment]
I don't have the crashlog, but I was in 1.15.1. The block I tried placing was a gem/metal/crystal block. After regenerating the ores, I didn't have the problem any more.

**Comment by thecatcore** [comment]
ok
