### ISSUE TITLE
Ores

### ISSUE THREAD

**Issue by Chewbaccaxe** [arthurbambou/Randomly-Adding-Anything#61]
I've been searching for ores with spectator for 1 hour and i can't find any. Is there any way that I can the spawn rate of them?

**Comment by Haskipend** [comment]
I was experiencing this problem when I played for the first time, but I set the "regen" property in the raa.json file to true and booted it up and it works. I think it didn't even generate them in the first place earlier, so regen just generated ore.

**Comment by TidalTempestBM** [comment]
i have the same issue and i can't find the right .json file to edit. can you direct me to the right folder?

**Comment by AdrickBoo** [comment]
I have the same problem I’ve downloaded a filler viewers and searched my pc but I can’t find it

**Comment by oliviathevampire** [comment]
We're currently investigating this problem

**Comment by Natalicatalie** [comment]
I just found this mod, and after a little while of searching, 2 hours or so, I have this same problem.

**Comment by flauntingspade4** [comment]
I also have this issue (If any help is needed for testing, I'm happy to help)

**Comment by Kitiraiku** [comment]
This also happened to me after joining my world for the second time, minecraft was turned off before i rejoined, always traveling doesn't seem to be the problem

**Comment by Kitiraiku** [comment]
i just noticed that the /locateRAA command does generate unexpected errors, and i didn't find structures as well, so it might be linked with the ore issue, but everything in the overworld that has relations with this mod seems to be affected by this

**Comment by deli73** [comment]
we haven't found any of the new ores outside (presumably) the spawn chunks, i think? new dimensions also seem to be generating without ores, as far as i can tell, though REI tells me the blocks and items are registered. -Nix

**Comment by oliviathevampire** [comment]
Try the newest github release

**Comment by oliviathevampire** [comment]
Should be fixed in newest github release
