### ISSUE TITLE
[1.15.1] Crashing immediately upon launch

### ISSUE THREAD

**Issue by Haskipend** [arthurbambou/Randomly-Adding-Anything#63]
To preface, I see that there have been some similar closed issues, but the information hasn't helped me. I apologize if it has been answered already.

I'm running the vanilla launcher of the 1.15.1 version with 1.15.1 fabric loader and api, but it just immediately crashes when I attempt to launch the game. It doesn't show any crash report.

**Comment by oliviathevampire** [comment]
Could you possibly try the 1.15.2 github version?

**Comment by Haskipend** [comment]
Would that be the Dev/1.15 one that it has defaulted to?
Actually I might have figured it out. It appears to be working!
