### ISSUE TITLE
[1.15.2] Bug with the Grinder of Tech Reborn

### ISSUE THREAD

**Issue by 11000matias** [arthurbambou/Randomly-Adding-Anything#64]
I found this bug once I installed this mod.
![2020-03-07_01 08 13](https://user-images.githubusercontent.com/18637199/76136441-3e593b80-6010-11ea-8f53-f6e6b6388175.png)
![2020-03-07_01 08 03](https://user-images.githubusercontent.com/18637199/76136443-3f8a6880-6010-11ea-8080-f0c857b2fde0.png)
![2020-03-07_01 08 10](https://user-images.githubusercontent.com/18637199/76136444-41542c00-6010-11ea-8b9a-abf0b19e9c74.png)
The Grinder is in a loop, in which it does not work

**Comment by thecatcore** [comment]
what version of the mod do you use?

**Comment by 11000matias** [comment]
I use 2.1.0 build 480
