### ISSUE TITLE
[1.15.2] Warning while loading Mods

### ISSUE THREAD

**Issue by CptLodomir** [arthurbambou/Randomly-Adding-Anything#65]
Could someone help me with this issue pls? I tried changing on different versions, but it didn't worked out.

![Bez tytułu](https://user-images.githubusercontent.com/61905062/76141885-8ad06580-6068-11ea-918c-55c82e7e22c5.png)
[Very good latest log .txt](https://github.com/vampire-studios/Randomly-Adding-Anything/files/4301691/Very.good.latest.log.txt)

**Comment by thecatcore** [comment]
RAA works with Fabric Loader not Forge Loader

**Comment by CptLodomir** [comment]
thanks :)
