### ISSUE TITLE
Ores no longer spawn

### ISSUE THREAD

**Issue by YoungJakobus** [arthurbambou/Randomly-Adding-Anything#66]
Hello, i started playing this mod this morning, and i only saw ores in sand and grass and i waited to go a bit further to find a good area to begin my journey. once i did, i went into some caves and got the basic minecraft materials, and i explored for an hour or so and never found any of the new ores or anything, it was quite disappointing, and don't know what happened, i even strip mined and didn't find anything. please help, thanks.

**Comment by thecatcore** [comment]
Duplicate of #61
