### ISSUE TITLE
Punching a block with a RAA sword (It had 5 Attack Speed, like two thirds of the other sword, thats an other issue) lags the game or the player position for a brief moment

### ISSUE THREAD

**Issue by Kitiraiku** [arthurbambou/Randomly-Adding-Anything#67]

**Comment by oliviathevampire** [comment]
What version do you use?

**Comment by Kitiraiku** [comment]
You mean the fabric version?


OliviaTheVampire <notifications@github.com> schrieb am Di., 10. März 2020,
11:43:

**Comment by Kitiraiku** [comment]
to be exact: fabric-loader-0.7.8+build.187-1.15.2 and the newest raa build

**Comment by oliviathevampire** [comment]
Any other mods?

**Comment by Kitiraiku** [comment]
no

**Comment by Kitiraiku** [comment]
i was in creative mode when i tested it

**Comment by oliviathevampire** [comment]
Anything in the log? Any video?

**Comment by Kitiraiku** [comment]
the log doesn't register anything, and it doesn't drop the game performance, what a weird bug

**Comment by oliviathevampire** [comment]
I've never seen this before, noone have reported it either

**Comment by Kitiraiku** [comment]
i think we can drop the case, because it might have something to do wit fabric, as vanilla swords are also affected by this, and to make this issue section not pointless, i have another issue that i can't craft blocks back to their materials, which should be easy to fix, if its unintended

**Comment by Kitiraiku** [comment]
but i have to say that so far this mod does a good job at what its supposed to do and when i first tried it, it mildly blew my expectations
