### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by BroehainIsHere** [arthurbambou/Randomly-Adding-Anything#7]
With the Fabric loader, the game immediately crashes if I try to launch it. I have no idea what the problem could be; I'm using the latest build of Fabric at version 1.14.4, which the mod works with.

**Comment by h4tena** [comment]
This happens to me too. Using the latest version of both Fabric and the mod.

**Comment by thecatcore** [comment]
I can't reproduce the crash, can you both try again with the latest version of Fabric Loader and Fabric API ?

**Comment by oliviathevampire** [comment]
might also happen because of old material file

**Comment by thecatcore** [comment]
Next release will fix the problem

**Comment by BroehainIsHere** [comment]
Nah man I'm being stupid, I forgot to install the API. Never used Fabric before now. Bit of a rookie mistake.

**Comment by thecatcore** [comment]
So we can close this
