### ISSUE TITLE
RAA world generation doesn't work with "regen" off after starting the game and joining the same world (might be related with the ores issue)

### ISSUE THREAD

**Issue by Kitiraiku** [arthurbambou/Randomly-Adding-Anything#73]
It seems like the game resets everything that is not player related to a earlier stage

**Comment by oliviathevampire** [comment]
This is known issue

**Comment by BlueGamer144** [comment]
I closed this issue for a reason

**Comment by BlueGamer144** [comment]
I tested it and it was wrong, so i will reedit it to be the generating issue

**Comment by Kitiraiku** [comment]
i reedited it

**Comment by oliviathevampire** [comment]
what do you with the title?

**Comment by oliviathevampire** [comment]
Should be fixed in newest github release
