### ISSUE TITLE
Ore textures are invisible while running raa with optifabric

### ISSUE THREAD

**Issue by Peleret** [arthurbambou/Randomly-Adding-Anything#76]
I'm running fabric loader 0.7.8 build.187-1.15.2 with these mods:
> optifabric 1.0.0-beta4
> Optifine 1.15.2 HD U G1 pre9
> raa 2.1.1 build.489
And I ran into this problem:
![2020-03-18_14 33 16](https://user-images.githubusercontent.com/33368610/76966365-23e36400-6926-11ea-851d-9a224ce86877.png)
It only happens with optifine/optifabric installed
I tried changing most settings and this bug won't stop
Other textures render just fine, only ores are glitched.

**Comment by oliviathevampire** [comment]
Optiifine is not compatible with this mod
