### ISSUE TITLE
Crash when placing blocks

### ISSUE THREAD

**Issue by BinxetyBinx** [arthurbambou/Randomly-Adding-Anything#77]
Happens with a few different ones, was in single player at the time testing things because I want to add the mod to my server. Made it so I was unable to rejoin that save file. Generated a crash report.

https://gist.githubusercontent.com/Cloak-Bot/203e19073d7147f5711bf8bf21e2b52d/raw/7d950e8827ba92665ca38882d544ba04e4937b37/crash.txt

**Comment by oliviathevampire** [comment]
Should be fixed in newest github release
