### ISSUE TITLE
World Generation/Rendering gone array

### ISSUE THREAD

**Issue by BinxetyBinx** [arthurbambou/Randomly-Adding-Anything#78]
I submitted an issue already about a crash when placing blocks, and this started happening right after creating a new world after that incident. The previous crash report mentioned a problem with rendering and in general I think it's just doing some really weird stuff. I came across a couple random blocks generated in the world that belong to this mod. Then the trees started doing this... As I flew around it just kept happening more and more. 

![2020-03-19_05 14 21](https://user-images.githubusercontent.com/47510715/77057450-f805c400-69a1-11ea-9f17-855ef5541c06.png)
![2020-03-19_05 15 17](https://user-images.githubusercontent.com/47510715/77057454-f936f100-69a1-11ea-9d69-85ec6856e078.png)
![2020-03-19_05 16 56](https://user-images.githubusercontent.com/47510715/77057458-fa681e00-69a1-11ea-98d0-9ac55dcb9fba.png)
![2020-03-19_05 17 35](https://user-images.githubusercontent.com/47510715/77057460-fb994b00-69a1-11ea-83b6-f1f01bcb36fa.png)

**Comment by BinxetyBinx** [comment]
Removing RAA eliminated the issue entirely.

**Comment by thecatcore** [comment]
Do you have Optifine installed?

**Comment by BinxetyBinx** [comment]
Optfine is not installed.

**Comment by dkmk100** [comment]
I've had similar issues
