### ISSUE TITLE
All ores despawn after Minecraft reeboot .

### ISSUE THREAD

**Issue by FreddieSilver** [arthurbambou/Randomly-Adding-Anything#81]
I am absolutely in love with this project. I hope you keep up the good work with this amazing gift.
There is a slight problem in this mod that makes it unplayable in a long term survival. After rebooting Minecraft  ( **Regen off** ), and coming back to my world, all the ores in the world disappear, including the ones in my inventory. I am currently playing with version **1.15.2 fabric**, and **raa-2.1.1+build.504**. My OS is WIndows 10. Please tell me if I am doing something wrong, and if not, please consider fixing it, that would make my quarantine much better! If you need any additional information, please don't hesitate asking. Thank you in advance!

**Comment by oliviathevampire** [comment]
Should be fixed in newest github release
