### ISSUE TITLE
Stone is too bouncy

### ISSUE THREAD

**Issue by subwe** [arthurbambou/Randomly-Adding-Anything#86]
I tested 9 different stone varieties, and all but two had extremely high jump heights off of them. This didn't happen with any of the other blocks in those dimensions, so could the chance of bounciness be way smaller?

**Comment by deli73** [comment]
both dimensions i've explored so far had very bouncy stone, so yeah, seconded

**Comment by oliviathevampire** [comment]
Will be fixed in 1.16 release
