### ISSUE TITLE
Crash on starting Minecraft

### ISSUE THREAD

**Issue by Minhoquinha** [arthurbambou/Randomly-Adding-Anything#91]
I downloaded the last beta version posted in Discord (RAA 2.4.0 beta 2 hotfix) and it crashes my Minecraft instantly, with the game not even starting. The RAA files that are supposed to be in config were not created. Here is the crash report:

[crash-2020-04-07_14.01.07-client.txt](https://github.com/vampire-studios/Randomly-Adding-Anything/files/4446084/crash-2020-04-07_14.01.07-client.txt)

**Comment by jaskarth** [comment]
Please use pastebin. Also, it would be better if you reported the discord builds on the discord and not on the github.

**Comment by Minhoquinha** [comment]
Aren't the discord builds the latest ones, and therefore the ones we have to test and report about?
Also, it says in README.txt that major bugs should be posted here instead.
And what do you mean by use pastebin?

**Comment by oliviathevampire** [comment]
@Minhoquinha you're using wrong version, the beta is for 20w14a

**Comment by jaskarth** [comment]
They are for testing yes, but they aren't fully public because we may add some stuff for people to give feedback to us about. The part in the readme doesn't apply to the beta builds because they're meant for discord use for the most part.
