### ISSUE TITLE
Ores not compatible between LAN worlds.

### ISSUE THREAD

**Issue by SmokyPig** [arthurbambou/Randomly-Adding-Anything#95]
Me and my friend have recently found this mod and wanted to join each others game. When I joined, it says I was missing all of his mod elements? How do I fix this? (I downloaded the same mod he has.)

**Comment by oliviathevampire** [comment]
you need same configs as him

**Comment by SmokyPig** [comment]
How would I do this?

**Comment by jaskarth** [comment]
Send them the entire raa folder in your configs folder.

**Comment by SmokyPig** [comment]
Thank you for your help, SuperCoder7979 and oliviathevampire.
